Saudigitus/dhis2-emis-android

- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/TopAppBar.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/theme/Type.kt
> [EMISANDROI-4]uniforming the app font and fixing the topbar subtitle text

- emis/src/main/java/org/saudigitus/emis/ui/components/Metadata.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> Emisandroi 2 - Resume component

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/TextViewComponent.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/FilterState.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> Emisandroi 6

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/dto/Absence.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Metadata.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/FilterState.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
- emis/src/main/java/org/saudigitus/emis/utils/Extensions.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
- emis/src/main/res/drawable/success_icon.xml
- emis/src/main/res/values/strings.xml
> [EMISANDROI-10] Update attendance status

- emis/src/main/java/org/saudigitus/emis/data/model/DefaultConfig.kt
- emis/src/main/java/org/saudigitus/emis/data/model/EMISConfigItem.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiViewModel.kt
…ear and datastore config update
> [EMISANDROI-12] Common fixies

- emis/src/main/java/org/saudigitus/emis/data/model/Stream.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Metadata.kt
- emis/src/main/java/org/saudigitus/emis/ui/favorites/ChipComponent.kt
- emis/src/main/java/org/saudigitus/emis/ui/favorites/FavoriteScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/favorites/FavoriteViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiViewModel.kt
> Emisandroi 14 - pre-polulate the filter with favorite

- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> fixing static section dropdown options

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/CalendarConfig.kt
- emis/src/main/java/org/saudigitus/emis/data/model/ClassPeriod.kt
- emis/src/main/java/org/saudigitus/emis/data/model/EMISConfig.kt
- emis/src/main/java/org/saudigitus/emis/data/model/Holiday.kt
- emis/src/main/java/org/saudigitus/emis/data/model/WeekDays.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/TopAppBar.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Utils.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
- emis/src/main/java/org/saudigitus/emis/utils/DateHelper.kt
- emis/src/main/java/org/saudigitus/emis/utils/Test.kt
> [EMISNADROI-17] School calendar implementation

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/EMISConfig.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
> [EMISANDROI-19] Fixing on select attendance status, null and indexoutofbounds exceptions

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Metadata.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> [EMISANDROI-25] Link homepage to students list

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/model/Subject.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceDetails.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceForm.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/subjects/SubjectScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/subjects/SubjectViewModel.kt
- emis/src/main/res/values/strings.xml
> [EMISANDROI-26] Performance redesign

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/FormRepository.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/FormRepositoryImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/AttendanceStatus.kt
- emis/src/main/java/org/saudigitus/emis/data/model/dto/AttendanceEntity.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendaceUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceOption.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/BulkAssignComponent.kt
- emis/src/main/java/org/saudigitus/emis/ui/base/BaseViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Metadata.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeItem.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/subjects/SubjectUIState.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/FilterState.kt
- emis/src/main/java/org/saudigitus/emis/utils/Test.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
- emis/src/main/res/values/strings.xml
> [EMISANDROI-29] feat: Implement bulk attendance

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
- emis/src/main/java/org/saudigitus/emis/utils/Extensions.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
> [EMISANDROI-31] feat: Load and validate status options from the datastore

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/model/mapper/SearchTeiModelMapper.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendaceUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/FormBuilder.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/InputField.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/mapper/TEICardMapper.kt
- emis/src/main/res/values/strings.xml
> [EMISANDROI-39] feat: implementing sync by tei, attendance screen state

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendaceUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceOptionContainer.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/FormBuilder.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/InputField.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/OptionsField.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/subjects/SubjectScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
> EMISANDROI-41

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/AttendanceStatus.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceOption.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceOptionContainer.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/BulkAssignComponent.kt
> EMISANDROI-43

- emis/src/main/java/org/saudigitus/emis/data/model/dto/Absence.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/mapper/TEICardMapper.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
> EMISANDROI-44

- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/ButtonComponents.kt
> [EMISNADROI-45] fix: fixing dialog summary on save

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/local/FormRepository.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/FormRepositoryImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/InputField.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
> EMISANDROI-47

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/ui/base/BaseViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/FilterState.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
- emis/src/main/java/org/saudigitus/emis/utils/Extensions.kt
> EMISANDROI-48

- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceComponents.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/base/BaseViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> EMISANDROI-50

- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeUiEvent.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/subjects/SubjectScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> feat: implementing program sync

- app/build.gradle.kts
- app/src/main/java/org/dhis2/usescases/about/AboutFragment.kt
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/values/strings.xml
- gradle/libs.versions.toml
> feat: implementing semis version

- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/Components.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt
- commons/src/main/java/org/dhis2/commons/navigator/AppNavigator.kt
- commons/src/main/java/org/dhis2/commons/navigator/NavigatorComponentProvider.kt
- commons/src/main/java/org/dhis2/commons/navigator/TeiDashboardComponentProvider.kt
- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/mapper/SearchTeiModelMapper.kt
- emis/src/main/java/org/saudigitus/emis/ui/base/BaseViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/teis/TeiScreen.kt
> feat: implementing tei dashboard navigation

- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
- emis/src/main/java/org/saudigitus/emis/utils/Utils.kt
1. SEMIS Android - Summary popup's Done/Cancel buttons become unclickable after first use
2. SEMIS Android - Filter not reopening after first use
> fix: fixing jira issues

- emis/src/main/java/org/saudigitus/emis/data/model/Summary.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceDialogs.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Utils.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
> fix: fixing summary dialogs and date validator

- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/service/RuleEngineRepository.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Extensions.kt
- emis/src/main/java/org/saudigitus/emis/utils/Transformations.kt
> feat: implementing option filters program rules

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/FormRepository.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/FormRepositoryImpl.kt
- emis/src/main/java/org/saudigitus/emis/di/AppModule.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/FormBuilder.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
> feat: implementing option filters program rules for performance form

- emis/src/main/java/org/saudigitus/emis/data/model/EMISConfigItem.kt
- emis/src/main/java/org/saudigitus/emis/data/model/Module.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Constants.kt
> feat: implementing dynamic modules visibility

- app/src/main/java/org/dhis2/usescases/login/ui/LoginScreen.kt
- emis/build.gradle.kts
- emis/src/main/java/org/saudigitus/emis/MainActivity.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/NavBar.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/analytics/AnalyticScreen.kt
> feat: adds analytics program screen and navigation

- emis/src/main/java/org/saudigitus/emis/ui/form/FormBuilder.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
> fix: [WDHIS-577] Unable to Update Performance

- emis/src/main/java/org/saudigitus/emis/data/local/DataManager.kt
- emis/src/main/java/org/saudigitus/emis/data/local/FormRepository.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/DataManagerImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/local/repository/FormRepositoryImpl.kt
- emis/src/main/java/org/saudigitus/emis/data/model/dto/AttendanceEntity.kt
- emis/src/main/java/org/saudigitus/emis/service/RuleEngineRepository.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceOptionContainer.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/ui/form/FormBuilder.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/performance/PerformanceViewModel.kt
- emis/src/main/java/org/saudigitus/emis/utils/Extensions.kt
- emis/src/main/java/org/saudigitus/emis/utils/Transformations.kt
> fix: form(attendance and performance)

- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/TopAppBar.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/Utils.kt
> feat: implementing calendar date range based on academic year

- emis/src/main/java/org/saudigitus/emis/data/model/EMISConfigItem.kt
- emis/src/main/java/org/saudigitus/emis/data/model/Filter.kt
- emis/src/main/java/org/saudigitus/emis/data/model/FilterDataElement.kt
- emis/src/main/java/org/saudigitus/emis/ui/attendance/AttendanceScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/components/DropdownComponet.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeScreen.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeUiState.kt
- emis/src/main/java/org/saudigitus/emis/ui/home/HomeViewModel.kt
> feat: Implementing filters based on datastore
